spring.application.name=my-market-app

server.port=8081
spring.r2dbc.url=r2dbc:h2:mem:///testdb?options=DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.username=sa
spring.datasource.password=

spring.main.web-application-type=reactive

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://keycloak:8080/realms/my-market-realm