spring.application.name=my-market-app

server.port=8080
spring.datasource.url=jdbc:h2:mem:usersdb;DB_CLOSE_DELAY=-1
spring.datasource.username=sa
spring.datasource.password=

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.jpa.hibernate.ddl-auto=none

# H2 (http://localhost:8080/h2-console)
spring.h2.console.enabled=true