spring.application.name=my-market-app

server.port=8080
spring.r2dbc.url=r2dbc:h2:mem:///testdb?options=DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.username=sa
spring.datasource.password=

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.jpa.hibernate.ddl-auto=none

# H2 (http://localhost:8080/h2-console)
spring.h2.console.enabled=true

payment.service.url=http://localhost:8081

spring.data.redis.host=localhost
spring.data.redis.port=6379

app.cache.items.ttl=300

spring.main.web-application-type=reactive

spring.security.oauth2.client.registration.shop-client.client-id=market
spring.security.oauth2.client.registration.shop-client.client-secret=secret
spring.security.oauth2.client.registration.shop-client.authorization-grant-type=client_credentials
spring.security.oauth2.client.provider.shop-client.token-uri=http://keycloak:8080/realms/my-market-realm/protocol/openid-connect/token
